[versions]
agp = "8.9.0"
gson = "2.10.1"
kotlin = "2.2.20"
compose = "1.9.3"
compose-material3 = "1.1.2"
androidx-activityCompose = "1.9.3"
jetbrainsKotlinJvm = "2.1.0"
androidx-lifecycle = "2.8.4"
kotlinCompilerEmbeddable = "2.2.20"
kotlinReflect = "2.2.20"
kotlinStdlib = "2.2.20"
runner = "1.5.2"
core = "1.5.0"
junit = "1.1.5"
symbolProcessingApi = "2.2.20-2.0.4"
kcp = "2.1.0"
compose-multiplatform = "1.9.3"
runtimeAndroid = "1.8.2"
navigationComposeVersion = "2.9.0-beta05"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlinCompilerEmbeddable" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "symbolProcessingApi" }
gradle-processing = {module = "org.jetbrains.kotlin:kotlin-gradle-plugin" ,version = "2.0.0"}
gradle-processing-api = {module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api",version = "2.0.0"}
kcp-native = {module = "org.jetbrains.kotlin:kotlin-backend-native",version  ="2.2.0"}

androidx-runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }

androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationComposeVersion" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "symbolProcessingApi" }
kcp = { id = "org.jetbrains.kotlin.plugin.compiler", version.ref = "kcp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }

publish = { id = "com.vanniktech.maven.publish", version = "0.30.0" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
